# Generated by Django 6.0.3 on 2026-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='muestras_fotos/')),
            ],
        ),
    ]
